### ISSUE TITLE
"Create RenderTexture Asset" button not showing

### ISSUE THREAD

**Issue by catigator** [RyanNielson/PixelCamera2D#4]
This button has not showed fro me since about the last couple of Unity updates - see photo: http://imgur.com/a/jaWTq

Not sure if this is on my end only?

**Comment by RyanNielson** [comment]
Haven't tested this out yet or used it in awhile. But could it be because you're in the debug/detailed view of the components?

**Comment by catigator** [comment]
Wow that was it, I feel very stupid now. Sorry for takibg up your time, and thanks for an awesome script!
